#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
npm run compile-readme
git add README.md
npm run typedoc
git add ./scripts/typedoc/typedoc-out.json

exec git diff --cached --name-only | npx cspell --no-summary --no-progress --no-must-find-files --file-list stdin