#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm exec lint-staged
pnpm compile-readme
git add README.md
pnpm typedoc
git add ./scripts/typedoc/typedoc-out.json

exec git diff --cached --name-only | pnpm exec cspell --no-summary --no-progress --no-must-find-files --file-list stdin