name: CD

on: workflow_dispatch

permissions:
  id-token: write

jobs:
  newVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MontyD/package-json-updated-action@1.0.1
        id: version-updated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      versionUpdated: ${{ steps.version-updated.outputs.has-updated }}
      version: ${{ steps.version-updated.outputs.current-package-version }}
  build:
    runs-on: ubuntu-latest
    needs: newVersion
    if: ${{ needs.newVersion.outputs.version-updated }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git tag v${{ needs.newVersion.outputs.version }}
      - run: git push --tags
