name: CI/CD

on:
  push:
    branches: [ "**" ]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run build
    
  newVersion:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: MontyD/package-json-updated-action@1.0.1
        id: version-updated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      versionUpdated: ${{ steps.version-updated.outputs.has-updated }}
      version: ${{ steps.version-updated.outputs.current-package-version }}
      
  publish:
    needs: newVersion
    if: ${{ needs.newVersion.outputs.version-updated }}
    runs-on: ubuntu-latest
    steps:
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  tag:
    needs: [publish, newVersion]
    runs-on: ubuntu-latest
    steps:
      - run: git tag v${{ needs.newVersion.outputs.version }}
      - run: git push --tags
