name: Docs CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/vuepress/**'

jobs:
  build_and_deploy_job:
    runs-on: mac-latest
    name: Build and Deploy Job
    strategy:
      matrix:
        node-version: [18.x]        
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm run ci-all
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GRASS_07FF9650F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/vuepress/.vuepress/dist"
          skip_app_build: true
      - name: Trigger Algolia docsearch crawler
        run: curl -H "Content-Type:application/json" --user 8f4b2817-400d-4d96-aa27-171a1165de82:${{ secrets.ALGOLIA_CRAWLER_KEY }} "https://crawler.algolia.com/api/1/"
      - name: Request URL Indexing
        run: pnpm run request-index
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}


